### ISSUE TITLE
Syntax error in docker-compose.yml

### ISSUE THREAD

**Issue by keesvanbochove** [thehyve/ohdsi-docker#5]
Error when executing bin/start:
```
$ bin/start
=== BUILDING DOCKER IMAGES ===
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.api value Additional properties are not allowed ('name' was unexpected)
$ docker --version
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
```
The offending part of `docker-compose.yml` seems to be https://github.com/thehyve/ohdsi-docker/blob/2e0afd4328ac6858635ad143d8e3294f839f4fde/docker-compose.yml#L246

**Comment by blootsvoets** [comment]
This property was added in docker-compose specification 3.5 (Docker-compose 1.18.0+, Docker 17.12.0+). I'll explicitly put that version at the beginning to make that more clear (ba9a9ac). Perhaps your docker-compose version is much older than your docker version? Install it separately from Docker as described here: https://docs.docker.com/compose/install/

**Comment by keesvanbochove** [comment]
@blootsvoets this is my docker-compose version:
```
$ docker-compose --version
docker-compose version 1.25.0, build unknown
$ apt-show-versions docker-compose
docker-compose:all/focal 1.25.0-1 uptodate
```

**Comment by blootsvoets** [comment]
Does ba9a9ac fix this for you? The property was [added by docker-compose file specification version 3.5](https://docs.docker.com/compose/compose-file/compose-versioning/#version-35).

**Comment by keesvanbochove** [comment]
This results in 
```
$ bin/start
=== BUILDING DOCKER IMAGES ===
ERROR: Version mismatch: file ./docker-compose.yml specifies version 3.5 but extension file ./docker-compose.scripts.yml uses version 3.0
```
